# Generated by Django 4.0.1 on 2022-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EBooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlee', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=None)),
                ('year', models.CharField(blank=True, max_length=100, null=None)),
                ('publisher', models.CharField(blank=True, max_length=200, null=None)),
                ('desc', models.CharField(blank=True, max_length=1000, null=None)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
            options={
                'ordering': ['titlee'],
            },
        ),
    ]
